# These are supported funding model platforms

github: mpurses
custom: ["venmo.com/MichaelPurses", "cash.app/$MichaelPurses", "paypal.com/cgi-bin/webscr?cmd=_donations&business=E59D22UD5FZGY&item_name=Sonder+donation&currency_code=USD"]
